server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingdb
    username: postgres
    password: AnisMohamadi5651$


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update